### ISSUE TITLE
Config File Schema / Example

### ISSUE THREAD

**Issue by promiseofcake** [home-assistant/hassio-cli#156]
Where is the documentation for the config file? Without it it's difficult to determine what is necessary to execute this tool.

**Comment by frenck** [comment]
The config file option is there for a developers perspective, actually not used in any production system.

The config file can be a JSON file containing the same keys as available on the command line arguments, next use the `--config` flag to specify the file.

Nevertheless, this tool is available via the HassOS CLI (developers debug mode), the Core SSH add-on, Community SSH & Web Terminal add-on, Community Visual Studio Code add-on and Community IDE add-on.

In those environments, this tool does not require any configuration, since it picks up its configuration from existing environment variables.

**Comment by mjrider** [comment]
further....
the config file takes key/value pairs, the same as the cli accept on the command line in yaml format
my development config file: `~/.homeassistant.yaml`
```yaml
---
log-level: debug
endpoint: "http://172.28.128.3:8080/"
```

**Comment by promiseofcake** [comment]
> actually not used in any production system

Interesting, I am using Hass.io on top of Raspbian -- is there somewhere specific I should be pointing the config for this to just work? Also to manage a local instance off-the node, it seems useful to be able to deploy this tool on my daily laptop for instance and configure it to point to my remote instance.

> the config file takes key/value pairs

Thank you, I was able to surmise that in looking through the code, I was thinking for a more general purpose audience having an example could be useful.

**Comment by frenck** [comment]
@promiseofcake The CLI meant to be run inside an add-on and was not designed for remote use.

Add-ons that have this CLI: the Core SSH add-on, Community SSH & Web Terminal add-on, Community Visual Studio Code add-on and Community IDE add-on.

**Comment by promiseofcake** [comment]
Thanks for the note.
