### ISSUE TITLE
Feature Request: Allow addons to be downgraded

### ISSUE THREAD

**Issue by deece** [home-assistant/hassio-cli#159]
Occasionally, an addon may fail in a disastrous way (eg. the current version of Node Red does not launch on aarch64). Rather than leaving users stuck with a non-functional house, or having to restore from a backup, we should provide a mechanism to reinstall an older version of an addon.

**Comment by pvizeli** [comment]
That is currently not possible. For this reason, there are snapshots of the system they can restore states.

**Comment by chaptergy** [comment]
> That is currently not possible

I think that is why it is a feature request. Unfortunately in situations where a downgrade would be required snapshots are not often available. Especially now with the "Auto update" feature, which probably wasn't implemented back when this issue was openend.

I would love to see this issue reopened.
